import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

const Detail: NextPage = () => {
  const router = useRouter();
  const { id } = router.query;
  const [detailData, setDetailData] = useState<any>(null);

  useEffect(() => {
    async function detail() {
      try {
        const url = `/api/blogs?id=${id}`;
        const req = await fetch(url);
        const data = await req.json();
        setDetailData(data);
      } catch (err) {
        console.log(err);
      }
    }

    detail();
  }, [id]);

  async function deleteBlog() {
    try {
      const url = `/api/blogs`;
      await fetch(url, {
        method: "DELETE",
        body: JSON.stringify({ id: `${id}` }),
      });
      router.back();
    } catch (err) {
      console.log(err);
    }
  }

  return (
    <>
      <Head>
        <title>Detail Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <button onClick={() => router.back()}>go back</button>
        <h1 className="text-7xl px-8 my-3">{detailData && detailData.title}</h1>
        <p>{detailData && detailData.author}</p>
        <p>{detailData && detailData.body}</p>

        <br />
        <br />
        <button onClick={deleteBlog}>Delete</button>
      </div>
    </>
  );
};

export default Detail;
