import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

const Home: NextPage = () => {
  const [data, setData] = useState<any[]>([]);

  async function blogs() {
    await fetch("/api/getallblogs")
      .then((res) => {
        return res.json();
      })
      .then((data) => {
        console.log(data);
        setData(data);
      })
      .catch((err) => console.log(err));
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello</h1>
        <button onClick={blogs}>Click me</button>

        {data &&
          data.map((index) => (
            <div key={index.id}>
              <h1>{index.title}</h1>
              <p>{index.author}</p>
              <p>{index.body}</p>
              <br />
              <br />
            </div>
          ))}
      </main>
    </>
  );
};

export default Home;
