import type { NextPage } from "next";
import Head from "next/head";

const NewBlog: NextPage = () => {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1 className="text-7xl px-8 my-3">New Blog Page</h1>
      </div>
    </>
  );
};

export default NewBlog;
